CREATE DATABASE IF NOT EXISTS tokpedsniper;
USE tokpedsniper;

CREATE TABLE IF NOT EXISTS items (
	id INT NOT NULL AUTO_INCREMENT, 
	name VARCHAR(256) NOT NULL,
	price VARCHAR(32) NOT NULL,
	url VARCHAR(512) NOT NULL,
	PRIMARY KEY (id)
);
